# Generated by cpp11: do not edit by hand

dust_sir_capabilities <- function() {
  .Call(`_sir_dust_sir_capabilities`)
}

dust_sir_gpu_info <- function() {
  .Call(`_sir_dust_sir_gpu_info`)
}

dust_cpu_sir_alloc <- function(r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_sir_dust_cpu_sir_alloc`, r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_sir_run <- function(ptr, step_end) {
  .Call(`_sir_dust_cpu_sir_run`, ptr, step_end)
}

dust_cpu_sir_simulate <- function(ptr, step_end) {
  .Call(`_sir_dust_cpu_sir_simulate`, ptr, step_end)
}

dust_cpu_sir_set_index <- function(ptr, r_index) {
  .Call(`_sir_dust_cpu_sir_set_index`, ptr, r_index)
}

dust_cpu_sir_update_state <- function(ptr, r_pars, r_state, r_step, r_set_initial_state) {
  .Call(`_sir_dust_cpu_sir_update_state`, ptr, r_pars, r_state, r_step, r_set_initial_state)
}

dust_cpu_sir_state <- function(ptr, r_index) {
  .Call(`_sir_dust_cpu_sir_state`, ptr, r_index)
}

dust_cpu_sir_step <- function(ptr) {
  .Call(`_sir_dust_cpu_sir_step`, ptr)
}

dust_cpu_sir_reorder <- function(ptr, r_index) {
  invisible(.Call(`_sir_dust_cpu_sir_reorder`, ptr, r_index))
}

dust_cpu_sir_resample <- function(ptr, r_weights) {
  .Call(`_sir_dust_cpu_sir_resample`, ptr, r_weights)
}

dust_cpu_sir_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_sir_dust_cpu_sir_rng_state`, ptr, first_only, last_only)
}

dust_cpu_sir_set_rng_state <- function(ptr, rng_state) {
  .Call(`_sir_dust_cpu_sir_set_rng_state`, ptr, rng_state)
}

dust_cpu_sir_set_data <- function(ptr, data) {
  .Call(`_sir_dust_cpu_sir_set_data`, ptr, data)
}

dust_cpu_sir_compare_data <- function(ptr) {
  .Call(`_sir_dust_cpu_sir_compare_data`, ptr)
}

dust_cpu_sir_filter <- function(ptr, step_end, save_trajectories, step_snapshot, min_log_likelihood) {
  .Call(`_sir_dust_cpu_sir_filter`, ptr, step_end, save_trajectories, step_snapshot, min_log_likelihood)
}

dust_cpu_sir_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_sir_dust_cpu_sir_set_n_threads`, ptr, n_threads))
}

dust_cpu_sir_n_state <- function(ptr) {
  .Call(`_sir_dust_cpu_sir_n_state`, ptr)
}
